version: '3'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./:/app
      - bot-data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=sqlite:///data/bot_database.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

volumes:
  bot-data: